services:
  user_api:
    hostname: user_api
    image: eduardogomesheleno/user_api:latest
    environment:
      GOOSE_MIGRATION_DIR: /app/database/migrations/
      GOOSE_TABLE: goose_migrations
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/chat_database_pswd
    networks:
      - traefik_traefik_proxy
      - user_database_network
      - rabbitmq_network
      - redis_network
    secrets:
      - chat_database_pswd
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.user-api.entrypoints=web"
        - "traefik.http.routers.user-api.rule=Host(`eduardodev.app.br`) && PathPrefix(`/user_api`)"
        - "traefik.http.middlewares.user-api-strip.stripprefix.prefixes=/user_api"
        - "traefik.http.routers.user-api.middlewares=user-api-strip"
        - "traefik.http.services.user-api.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.hostname == instance2

networks:
  traefik_traefik_proxy:
    driver: overlay
    attachable: true
    external: true

  user_database_network:
    driver: overlay
    external: true

  rabbitmq_network:
    driver: overlay
    external: true

  redis_network:
    driver: overlay
    external: true

secrets:
  chat_database_pswd:
    external: true
