
name: Deploy to Docker Swarm

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t eduardogomesheleno/user_api:latest .
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push eduardogomesheleno/user_api:latest

      - name: Trigger Portainer redeploy webhook
        run: |
          curl -X POST http://portainer.eduardodev.app.br/api/stacks/webhooks/a87a3a29-25d8-4a64-869e-417bb33b287f
