
name: Deploy to Docker Swarm

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t eduardogomesheleno/rt_server:latest .
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push eduardogomesheleno/rt_server:latest

      - name: Trigger Portainer redeploy webhook
        run: |
          curl -X POST http://portainer.eduardodev.app.br/api/stacks/webhooks/09415d63-23d8-4689-81a3-fb6b56c0ab86
